### PR TITLE
Issue#11 upgrading gradle4.0 cannot add child spec exception

### PR DESCRIPTION
**Pull request by mat013**
I have upgrade to 3.5 as 4.0.1 maybe to recent for most people.

The issue when upgrading was that the dar task is a copy task. And it is not allowed to modify the files to be copied while it is executing.

The implementation is that I have splitted the dar task into two tasks:
* Configuring the dar task, which is done in the darConfiguration task
* Copy the files, which is done in the dar task

### CODE REVIEW

**Comment by mat013** [comment]
I can see that the travis fails due to java8 is not supported.

Would it be wrong that we could upgrade to java8? Alternatively make a new version?

**Comment by flstaats** [comment]
You can fix this by changing the build.gradle (found by trial and error bisecting to get the highest versions that still supported Java 1.7 jar file format).  Could you please try this and see if the the travisci build will work.  I have a local build working with both Java 1.8 and 1.7 but would really like the offical community build to support Gradle 4.0.2/4.1

```
compile "com.xebialabs.deployit.engine:remote-booter:2016.2.2"
compile group: 'com.google.guava', name: 'guava', version: '21.0'
```

to:

```
compile "com.xebialabs.deployit.engine:remote-booter:2015.6.10"
compile "nl.javadude.scannit:scannit:1.4.1"
compile "com.jcraft:jzlib:1.1.3"
compile "com.google.guava:guava:22.0-android"
```

Note: scannit and jzip were upgraded since the repos no longer hold the older buggy versions.  guava:22.0-android is Java 1.6 & 1.7 compatible.  And remote-booter:2015.6.10 was the last version built that is Java 1.7 compatible.

**Comment by jdewinne** [comment]
Shouldn't the `.travis.yml` file contain `dist: trusty` to have Java 8 support?
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

**Comment by jdewinne** [comment]
@mat013 is it possible for you to allow changes to this PR as also described in: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by jdewinne** [comment]
I've incorporated this PR by putting it on a separate branch and recreating it. The release still needs to take place.
Closing this PR for now

**Comment by mat013** [comment]
I was on holiday... I guess nothing more is needed otherwise let me know

**Comment by jdewinne** [comment]
All set. I've incorporated your changes (thanks for that!)

**Pull request closed without merging**
